#!/bin/bash
# Railway Project Connection & Diagnostic Script
# Project: pet_roasting
# Project ID: d3e9f8f4-cdca-4825-9ec4-f7fa9844d266
# Environment ID: d07ed2df-e646-45dd-9510-b40b1ceee70d

PROJECT_ID="d3e9f8f4-cdca-4825-9ec4-f7fa9844d266"
ENVIRONMENT_ID="d07ed2df-e646-45dd-9510-b40b1ceee70d"
PROJECT_NAME="pet_roasting"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🚂 Railway Project Diagnostics"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Project Name: $PROJECT_NAME"
echo "Project ID: $PROJECT_ID"
echo "Environment ID: $ENVIRONMENT_ID"
echo ""

# Check if Railway CLI is installed
if command -v railway &> /dev/null; then
    echo "✅ Railway CLI detected"
    echo ""
    echo "📋 Available Commands:"
    echo ""
    echo "1. Login to Railway:"
    echo "   railway login"
    echo ""
    echo "2. Link to project:"
    echo "   railway link $PROJECT_ID"
    echo ""
    echo "3. View project status:"
    echo "   railway status"
    echo ""
    echo "4. View environment variables:"
    echo "   railway variables"
    echo ""
    echo "5. View logs:"
    echo "   railway logs"
    echo ""
    echo "6. Open in browser:"
    echo "   railway open"
    echo ""
    echo "7. Deploy:"
    echo "   railway up"
    echo ""
else
    echo "⚠️  Railway CLI not installed"
    echo ""
    echo "Install Railway CLI:"
    echo "  npm i -g @railway/cli"
    echo ""
    echo "Or use Railway Dashboard:"
    echo "  https://railway.app/project/$PROJECT_ID"
    echo ""
fi

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  📊 Railway Dashboard Links"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Main Dashboard:"
echo "  https://railway.app/project/$PROJECT_ID"
echo ""
echo "Environment:"
echo "  https://railway.app/project/$PROJECT_ID?environmentId=$ENVIRONMENT_ID"
echo ""
echo "Deployments:"
echo "  https://railway.app/project/$PROJECT_ID/deployments"
echo ""
echo "Variables:"
echo "  https://railway.app/project/$PROJECT_ID/variables"
echo ""
echo "Logs:"
echo "  https://railway.app/project/$PROJECT_ID/logs"
echo ""
echo "Settings:"
echo "  https://railway.app/project/$PROJECT_ID/settings"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  ✅ Required Environment Variables"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://railway.app/project/$PROJECT_ID/variables"
echo ""
echo "Add these variables:"
echo ""
echo "FAL_API_KEY=0d44c9a0-5679-4338-9f14-055fa0907d5f:6e3f241a600df52476c1bb414dff5e4a"
echo "FAL_BASE_URL=https://queue.fal.run"
echo "FAL_MODEL_ID=fal-ai/minimax-video"
echo "USE_REDIS=true"
echo "VIDEO_STORAGE_PATH=storage/videos"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔍 Diagnostic Steps"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Check Latest Deployment:"
echo "   https://railway.app/project/$PROJECT_ID/deployments"
echo ""
echo "2. Check Build Logs:"
echo "   - Click on latest deployment"
echo "   - Review build logs for errors"
echo ""
echo "3. Check Runtime Logs:"
echo "   https://railway.app/project/$PROJECT_ID/logs"
echo "   - Look for 'Application startup complete'"
echo "   - Check for ERROR messages"
echo ""
echo "4. Test Health Endpoint:"
echo "   - Get your Railway URL from Settings → Networking"
echo "   - Test: curl https://your-app.railway.app/healthz"
echo ""
echo "5. Check Variables:"
echo "   - Ensure all required variables are set"
echo "   - Verify FAL_API_KEY is correct"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🛠️  Quick Fixes"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "If deployment fails:"
echo "  1. Check build logs for specific errors"
echo "  2. Verify all environment variables are set"
echo "  3. Try redeploying from Deployments tab"
echo ""
echo "If app crashes:"
echo "  1. Check runtime logs for error messages"
echo "  2. Verify FAL_API_KEY is correct"
echo "  3. Check Redis connection (if enabled)"
echo ""
echo "If health check fails:"
echo "  1. Ensure app is running (check logs)"
echo "  2. Verify PORT is set correctly"
echo "  3. Check networking settings"
echo ""

echo "✅ Run this script anytime to get Railway connection info!"
echo ""
